package ai625;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Amos on 2017/9/15.
 */
public class Node implements Comparable<Node> {

    // State
    State state;

    // Parent
    Node parent;

    // Action taken by Parent format: (from,to)
    Action action;

    // Path cost
    long pathCost;

    // h function
    long rank;

    // Initialize node
    public Node(int block, int stack, boolean isRandom) {

        state = new State(block, stack, false);
        // Root node
        parent = null;
        action = null;
        pathCost = 0;
        rank = 0;
    }

    // Node generated by actions
    public Node(State prevState, Node parent, Action action, long pathCost, long rank) {
        this.state = new State(prevState, action);
        this.parent = parent;
        this.action = action;
        this.pathCost = pathCost;
        this.rank = rank;
    }


    public List<Node> generateSuccessors() {
        List<Node> res = new ArrayList<>();

        List<List<Integer>> currentBoard = state.board;
        // Generate all the moves
        for(int i=1; i<=state.stack; i++) {
            List<Integer> fromStack = currentBoard.get(i);
            // Skip empty stacks
            if(fromStack.isEmpty()) {
                continue;
            }
            for(int j=1; j<=state.stack; j++) {
                if(i == j) {
                    continue;
                }
                // Perform the move
                Node newNode = new Node(state, this, new Action(i,j), pathCost+1, rank+1);

                res.add(newNode);
            }
        }
        return res;
    }



    // Used for priority queue
    @Override
    public int compareTo(Node o) {
        return Long.compare(rank, o.rank);
    }
}
